name: Slides overview 2022

on:
  push:
    branches: [main]
    # paths:
    #   - src/**
  schedule:
    - cron: "0 14 * * 5"

jobs:
  build_latex:
    runs-on: ubuntu-20.04
    container: archlinux:base-devel
    env:
      PACKAGES: "pandoc texlive-latexextra texlive-pictures ttf-fira-code"
      AUR_PACKAGES: "otf-firamath noto-fonts-emoji-apple"
    steps:
      - uses: actions/checkout@v2

      - name: Install packages for Arch linux
        run: |
          pacman -Syuq $PACKAGES --needed --noconfirm > /dev/null 2>&1
          for package in ${AUR_PACKAGES[@]}; do
            curl -LO https://aur.archlinux.org/cgit/aur.git/snapshot/${package}.tar.gz
            tar -xvf ${package}.tar.gz
            ls
          done #>/dev/null 2>&1
          while read -r in; do
            pushd "${in}"
            makepkg -sirc --cleanbuild --noconfirm #>/dev/null 2>&1
            popd
          done <packages.x86_64 >/dev/null 2>&1
          pushd src
          dates=$(ls -d */ | tr '/' ' ')
          popd
          pacman -Qi otf-firamath noto-fonts-emoji-apple
          for d in "${dates[@]}"; do echo ${d} ; done
          pandoc src/${d}/*.md -t beamer -V lang=es --pdf-engine=lualatex -o ${d}.pdf
          mkdir -p public && mv 2022-0*-*.pdf public

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: public
