name: Slides overview 2022

on:
  push:
    branches: [main]
    # paths:
    #   - src/**
  schedule:
    - cron: "0 14 * * 5"

jobs:
  build_latex:
    runs-on: ubuntu-20.04
    container: archlinux:base-devel
    env:
      PACKAGES: "pandoc texlive-latexextra texlive-pictures ttf-fira-code"
      AUR_PACKAGES: "otf-firamath noto-fonts-emoji-apple"
    steps:
      - uses: actions/checkout@v2

      - name: Test Arch linux
        run: |
          whoami
          pacman -Syyuq $PACKAGES --needed --noconfirm
          dates=('2022-01-15' '2022-01-16' '2022-01-22' '2022-01-23' '2022-01-29' '2022-01-30' '2022-02-05' '2022-02-06' '2022-02-12' '2022-02-13')
          echo $PACKAGES
      # for d in "${dates[@]}"; do pandoc src/${d}/*.md -t beamer -V lang=es --pdf-engine=lualatex -o ${d}.pdf ; done
      # mkdir -p public && mv 2022-0*-*.pdf public

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: public
