name: Slides overview 2022

on:
  push:
    branches: [main]
    # paths:
    #   - src/**
  schedule:
    - cron: "0 14 * * 5"

jobs:
  build_latex:
    runs-on: ubuntu-20.04
    container: ghcr.io/cpp-review-dune/introductory-review/aur
    env:
      PACKAGES: "pandoc texlive-latexextra texlive-pictures ttf-fira-code"
      AUR_PACKAGES: "otf-firamath noto-fonts-emoji-apple"
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          whoami
          yay --version
          # useradd -l -md /home/aur -s /bin/bash aur && passwd -d aur && echo 'aur ALL=(ALL) ALL' > /etc/sudoers.d/aur
          # su - aur
          # whoami
          # sudo pacman -Syuq $PACKAGES --needed --noconfirm #> /dev/null 2>&1
          # cd ~
          # curl -LO https://aur.archlinux.org/cgit/aur.git/snapshot/otf-firamath.tar.gz
          # tar -xvf otf-firamath
          # cd otf-firamath
          # makepkg -si --noconfirm
          # pushd src
          # dates=$(ls -d */ | tr '/' ' ')
          # popd
          # pacman -Qi otf-firamath noto-fonts-emoji-apple
          # for d in "${dates[@]}"; do echo ${d} ; done
          # pandoc src/${d}/*.md -t beamer -V lang=es --pdf-engine=lualatex -o ${d}.pdf
          # mkdir -p public && mv 2022-0*-*.pdf public

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: public
